# Generated by Django 3.2.18 on 2023-11-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='programador_jobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1, null=True)),
                ('nombre_tarea', models.CharField(max_length=100)),
                ('dias_semana', models.CharField(max_length=50, null=True)),
                ('tipo_horario', models.CharField(max_length=50, null=True)),
                ('horario_rango', models.CharField(max_length=20, null=True)),
                ('job_ejecutar', models.CharField(max_length=200, null=True)),
                ('emails_notificacion', models.CharField(max_length=500, null=True)),
                ('usuario_registro', models.CharField(max_length=20, null=True)),
                ('terminal_registro', models.CharField(max_length=15, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario_modificacion', models.CharField(max_length=20, null=True)),
                ('terminal_modificacion', models.CharField(max_length=15, null=True)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
        ),
    ]
