# Generated by Django 3.2.18 on 2024-01-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programador_jobs',
            name='tipo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
