# Generated by Django 3.2.18 on 2024-02-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0002_programador_jobs_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programador_jobs',
            name='num_veces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
