# Generated by Django 3.2.18 on 2023-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0002_auto_20231122_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='programador_jobs',
            name='job_descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
