# Generated by Django 3.2.18 on 2024-02-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0003_programador_jobs_num_veces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programador_jobs',
            name='emails_notificacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
