# Generated by Django 3.2.18 on 2023-11-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0003_programador_jobs_job_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programador_jobs',
            name='fecha_ultima_ejecucion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='programador_jobs',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
