# Generated by Django 3.2.18 on 2024-01-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0004_auto_20231123_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='programador_jobs',
            name='estado_ejecucion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
