# Generated by Django 3.2.18 on 2023-09-17 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='black_gray_list',
            fields=[
                ('imei', models.BigIntegerField(error_messages={'unique': 'Codigo IMEI ya se encuentra registrado'}, primary_key=True, serialize=False)),
                ('list', models.CharField(max_length=1, null=True)),
                ('last_imsi', models.BigIntegerField(blank=True, null=True)),
                ('operator_code', models.CharField(max_length=15, null=True)),
                ('actvt_date', models.DateTimeField(auto_now_add=True)),
                ('actvt_obs', models.CharField(max_length=255, null=True)),
                ('code', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'black_gray_list',
            },
        ),
        migrations.CreateModel(
            name='files_imei_bulk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('archivo_csv', models.CharField(max_length=50)),
                ('total_encontrado', models.IntegerField(blank=True, null=True)),
                ('total_error', models.IntegerField(blank=True, null=True)),
                ('total_ok', models.IntegerField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_archivo_procesando', models.DateTimeField(blank=True, null=True)),
                ('fecha_archivo_finalizado', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_registro', models.CharField(max_length=20)),
                ('ip_registro', models.CharField(max_length=50)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_actualizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_actualizacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'files_imei_bulk',
            },
        ),
        migrations.CreateModel(
            name='log_imei_eir',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('accion', models.CharField(max_length=50)),
                ('imei', models.BigIntegerField()),
                ('operadora', models.CharField(max_length=50, null=True)),
                ('lista', models.CharField(max_length=50, null=True)),
                ('razon', models.CharField(max_length=1000, null=True)),
                ('origen', models.CharField(max_length=50, null=True)),
                ('fecha_bitacora', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('usuario_descripcion', models.CharField(max_length=50, null=True)),
                ('ip_transaccion', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'log_imei_eir',
            },
        ),
        migrations.AddIndex(
            model_name='log_imei_eir',
            index=models.Index(fields=['imei'], name='log_imei_ei_imei_3c5ca2_idx'),
        ),
    ]
