# Generated by Django 3.2.18 on 2023-09-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black_gray_list',
            name='code',
            field=models.SmallIntegerField(null=True),
        ),
    ]
