# Generated by Django 3.2.18 on 2024-01-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imei', '0002_alter_black_gray_list_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black_gray_list',
            name='operator_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
