# Generated by Django 3.2.18 on 2024-01-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imei', '0003_alter_black_gray_list_operator_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_imei_bulk',
            name='accion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
