# Generated by Django 3.2.18 on 2024-01-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imei', '0004_files_imei_bulk_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_imei_bulk',
            name='accion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
