# Generated by Django 3.2.18 on 2024-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imei', '0005_alter_files_imei_bulk_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='black_gray_list',
            name='source',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
