# Generated by Django 3.2.18 on 2024-09-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imei', '0006_black_gray_list_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_code', models.CharField(blank=True, max_length=15, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'operator',
            },
        ),
    ]
