# Generated by Django 3.2.18 on 2024-09-22 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imei', '0007_operator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='operator',
        ),
    ]
