# Generated by Django 3.2.18 on 2024-09-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imei', '0008_delete_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='operator',
            fields=[
                ('operator_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('operator_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'operator',
            },
        ),
    ]
