openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/acciones/:
    get:
      operationId: api_acciones_retrieve
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/login:
    post:
      operationId: api_auth_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/auth/myInformation:
    get:
      operationId: api_auth_myInformation_retrieve
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/auth/register_user:
    post:
      operationId: api_auth_register_user_create
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/token/refresh:
    post:
      operationId: api_auth_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/menu_opcion/:
    get:
      operationId: api_menu_opcion_retrieve
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/roles/:
    get:
      operationId: api_roles_retrieve
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/roles_menu/:
    get:
      operationId: api_roles_menu_list
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RolesMenu'
          description: ''
    post:
      operationId: api_roles_menu_create
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolesMenuRegistro'
          description: ''
  /api/roles_menu/{id}/:
    patch:
      operationId: api_roles_menu_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolesMenuActualizar'
          description: ''
  /api/roles_menuaccion/:
    get:
      operationId: api_roles_menuaccion_list
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RolesMenuAccion'
          description: ''
    post:
      operationId: api_roles_menuaccion_create
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolesMenuAccionRegistro'
          description: ''
  /api/roles_menuaccion/{id}/:
    patch:
      operationId: api_roles_menuaccion_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolesMenuAccionActualizar'
          description: ''
  /api/transaction/lista_negra/:
    post:
      operationId: api_transaction_lista_negra_create
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaNegraRegistro'
          description: ''
  /schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    ListaNegraRegistro:
      type: object
      properties:
        imsi:
          type: string
          maxLength: 15
        source:
          type: string
          nullable: true
          maxLength: 50
      required:
      - imsi
    RolesMenu:
      type: object
      properties:
        rolmenu_id:
          type: integer
          readOnly: true
        estado:
          type: string
          maxLength: 1
        rol_id_id:
          type: integer
          nullable: true
          readOnly: true
        rol_descripcion:
          type: string
          nullable: true
          maxLength: 50
        menu_id_id:
          type: integer
          nullable: true
          readOnly: true
        menu_descripcion:
          type: string
          maxLength: 50
        fecha_creacion:
          type: string
          format: date-time
          readOnly: true
        usuario_creacion:
          type: string
          maxLength: 15
        ip_creacion:
          type: string
          maxLength: 20
        fecha_modificacion:
          type: string
          format: date-time
          nullable: true
        usuario_modificacion:
          type: string
          nullable: true
          maxLength: 15
        ip_modificacion:
          type: string
          nullable: true
          maxLength: 20
      required:
      - estado
      - fecha_creacion
      - ip_creacion
      - menu_descripcion
      - menu_id_id
      - rol_id_id
      - rolmenu_id
      - usuario_creacion
    RolesMenuAccion:
      type: object
      properties:
        rolmenuaccion_id:
          type: integer
          readOnly: true
        estado:
          type: string
          maxLength: 1
        rolmenu_id:
          type: integer
          nullable: true
        accion_id:
          type: integer
          nullable: true
        usuario_creacion:
          type: string
          maxLength: 15
        ip_creacion:
          type: string
          maxLength: 20
        fecha_modificacion:
          type: string
          format: date-time
          nullable: true
        usuario_modificacion:
          type: string
          nullable: true
          maxLength: 15
        ip_modificacion:
          type: string
          nullable: true
          maxLength: 20
      required:
      - estado
      - ip_creacion
      - rolmenuaccion_id
      - usuario_creacion
    RolesMenuAccionActualizar:
      type: object
      properties:
        estado:
          type: string
          maxLength: 1
        rolmenu_id:
          type: integer
          nullable: true
        accion_id:
          type: integer
          nullable: true
        fecha_modificacion:
          type: string
          format: date-time
          nullable: true
        usuario_modificacion:
          type: string
          nullable: true
          maxLength: 15
        ip_modificacion:
          type: string
          nullable: true
          maxLength: 20
      required:
      - estado
    RolesMenuAccionRegistro:
      type: object
      properties:
        rolmenuaccion_id:
          type: integer
          readOnly: true
        estado:
          type: string
          maxLength: 1
        rolmenu_id:
          type: integer
          nullable: true
        accion_id:
          type: integer
          nullable: true
        usuario_creacion:
          type: string
          maxLength: 15
        ip_creacion:
          type: string
          maxLength: 20
      required:
      - estado
      - ip_creacion
      - rolmenuaccion_id
      - usuario_creacion
    RolesMenuActualizar:
      type: object
      properties:
        estado:
          type: string
          maxLength: 1
        rol_id:
          type: integer
          nullable: true
        rol_descripcion:
          type: string
          nullable: true
          maxLength: 50
        menu_id:
          type: integer
          nullable: true
        menu_descripcion:
          type: string
          maxLength: 50
        fecha_modificacion:
          type: string
          format: date-time
          nullable: true
        usuario_modificacion:
          type: string
          nullable: true
          maxLength: 15
        ip_modificacion:
          type: string
          nullable: true
          maxLength: 20
      required:
      - estado
      - menu_descripcion
    RolesMenuRegistro:
      type: object
      properties:
        rolmenu_id:
          type: integer
          readOnly: true
        estado:
          type: string
          maxLength: 1
        rol_id:
          type: integer
          nullable: true
        rol_descripcion:
          type: string
          nullable: true
          maxLength: 50
        menu_id:
          type: integer
          nullable: true
        menu_descripcion:
          type: string
          maxLength: 50
        fecha_creacion:
          type: string
          format: date-time
          readOnly: true
        usuario_creacion:
          type: string
          maxLength: 15
        ip_creacion:
          type: string
          maxLength: 20
      required:
      - estado
      - fecha_creacion
      - ip_creacion
      - menu_descripcion
      - rolmenu_id
      - usuario_creacion
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
