# Generated by Django 3.2.18 on 2023-06-02 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('accion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=50)),
                ('id_componente_html', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('ip_creacion', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.CharField(max_length=15, null=True)),
                ('ip_modificacion', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuOpcion',
            fields=[
                ('menu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=50)),
                ('url_page', models.CharField(max_length=100)),
                ('id_componente_html', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('ip_creacion', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.CharField(max_length=15, null=True)),
                ('ip_modificacion', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rol_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('ip_creacion', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.CharField(max_length=15, null=True)),
                ('ip_modificacion', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolesMenu',
            fields=[
                ('rolmenu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('rol_descripcion', models.CharField(max_length=50, null=True)),
                ('menu_descripcion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('ip_creacion', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.CharField(max_length=15, null=True)),
                ('ip_modificacion', models.CharField(max_length=20, null=True)),
                ('menu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.menuopcion')),
                ('rol_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.roles')),
            ],
        ),
        migrations.CreateModel(
            name='RolesMenuAccion',
            fields=[
                ('rolmenuaccion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('ip_creacion', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.CharField(max_length=15, null=True)),
                ('ip_modificacion', models.CharField(max_length=20, null=True)),
                ('accion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.acciones')),
                ('rolmenu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.rolesmenu')),
            ],
        ),
    ]
