# Generated by Django 3.2.18 on 2023-06-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='estado',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
