# Generated by Django 3.2.18 on 2023-06-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_auto_20230602_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='ip_modificacion',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='usuario_modificacion',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='ip_modificacion',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='usuario_modificacion',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='roles',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='ip_modificacion',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='roles',
            name='usuario_modificacion',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='rolesmenu',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rolesmenu',
            name='ip_modificacion',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='rolesmenu',
            name='usuario_modificacion',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='rolesmenuaccion',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rolesmenuaccion',
            name='ip_modificacion',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='rolesmenuaccion',
            name='usuario_modificacion',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
    ]
