# Generated by Django 3.2.18 on 2023-06-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_auto_20230602_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesmenu',
            name='ip_modificacion',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rolesmenu',
            name='usuario_modificacion',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rolesmenuaccion',
            name='ip_modificacion',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rolesmenuaccion',
            name='usuario_modificacion',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
