# Generated by Django 3.2.18 on 2023-06-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_auto_20230602_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='accion_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
