# Generated by Django 3.2.18 on 2024-01-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_roles_rol_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOpcionPadre',
            fields=[
                ('menu_padre_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('ip_creacion', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(blank=True, default=None, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, default=None, max_length=15)),
                ('ip_modificacion', models.CharField(blank=True, default=None, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='menuopcion',
            name='menu_id_padre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
