# Generated by Django 3.2.18 on 2023-06-02 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='black_imsi',
            fields=[
                ('imsi', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50, null=True)),
                ('register', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='log_aprov_eir',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('accion', models.CharField(max_length=50)),
                ('imsi', models.CharField(max_length=100, null=True)),
                ('operadora', models.CharField(max_length=100, null=True)),
                ('lista', models.CharField(max_length=100, null=True)),
                ('razon', models.CharField(max_length=100, null=True)),
                ('origen', models.CharField(max_length=100, null=True)),
                ('fecha_bitacora', models.DateTimeField(auto_now_add=True, verbose_name='When Created')),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('usuario_descripcion', models.CharField(max_length=50, null=True)),
                ('usuario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
