# Generated by Django 3.2.18 on 2023-06-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_aprov_eir',
            name='fecha_bitacora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
