# Generated by Django 3.2.18 on 2023-06-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0002_alter_log_aprov_eir_fecha_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black_imsi',
            name='register',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
