# Generated by Django 3.2.18 on 2023-06-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0003_alter_black_imsi_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black_imsi',
            name='imsi',
            field=models.CharField(error_messages={'unique': 'Codigo IMSI ya se encuentra registrado'}, max_length=15, primary_key=True, serialize=False),
        ),
    ]
