# Generated by Django 3.2.18 on 2023-06-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0005_auto_20230607_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black_imsi',
            name='imsi',
            field=models.IntegerField(error_messages={'unique': 'Codigo IMSI ya se encuentra registrado'}, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log_aprov_eir',
            name='imsi',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
