# Generated by Django 3.2.18 on 2023-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0009_auto_20230623_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='files_process_bulk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('archivo_csv', models.CharField(max_length=50)),
                ('total_encontrado', models.IntegerField(blank=True, null=True)),
                ('total_error', models.IntegerField(blank=True, null=True)),
                ('total_ok', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_registro', models.CharField(max_length=20)),
                ('ip_registro', models.CharField(max_length=50)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_actualizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_actualizacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
