# Generated by Django 3.2.18 on 2023-06-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0012_files_process_bulk_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_process_bulk',
            name='fecha_archivo_finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files_process_bulk',
            name='fecha_archivo_procesando',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
