# Generated by Django 3.2.18 on 2023-06-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0014_auto_20230627_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_aprov_eir',
            name='ip_transaccion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
