# Generated by Django 3.2.18 on 2023-07-28 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0016_auto_20230703_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='imei_imsi_block',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('central', models.CharField(max_length=100)),
                ('imei', models.BigIntegerField()),
                ('imsi', models.BigIntegerField()),
                ('codigo1', models.CharField(max_length=100)),
                ('codigo2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='imei_imsi_block',
            index=models.Index(fields=['imei', 'imsi'], name='lista_negra_imei_b38e3b_idx'),
        ),
    ]
