# Generated by Django 3.2.18 on 2023-07-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0018_auto_20230729_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imei_imsi_block',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imei_imsi_block',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
