# Generated by Django 3.2.18 on 2023-07-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0019_auto_20230729_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='imei_imsi_block',
            name='tecnologia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
