# Generated by Django 3.2.18 on 2023-10-16 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0020_imei_imsi_block_tecnologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_api_actions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('action', models.CharField(max_length=2)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('api_url', models.CharField(blank=True, max_length=100, null=True)),
                ('insert_register', models.DateTimeField(default=django.utils.timezone.now)),
                ('insert_ip', models.CharField(blank=True, max_length=25)),
                ('update_register', models.DateTimeField(blank=True, null=True)),
                ('update_ip', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
