# Generated by Django 3.2.18 on 2024-01-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_negra', '0022_files_process_bulk_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_process_bulk',
            name='accion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
